# Generated by Django 4.1.2 on 2023-01-28 10:19

from django.db import migrations, models
import django.db.models.deletion
import submission.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_assignment_assignment_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionToken_token', models.CharField(max_length=10)),
                ('sessionToken_expired', models.BooleanField(default=False)),
                ('sessionToken_validity_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'SessionToken',
                'verbose_name_plural': 'SessionTokens',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date_time', models.DateTimeField(auto_now=True)),
                ('submission_reg_no', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_file', models.FileField(null=True, upload_to=submission.models.assin_sub_path)),
                ('submission_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.assignment')),
                ('submission_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('submission_session_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.sessiontoken')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
