# Generated by Django 4.1.2 on 2022-10-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionToken_token', models.CharField(max_length=10)),
                ('sessionToken_valid_till', models.TimeField()),
                ('sessionToken_expired', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SessionToken',
                'verbose_name_plural': 'SessionTokens',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.TimeField(auto_now=True)),
                ('submission_reg_no', models.CharField(max_length=20)),
                ('submission_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.assignment')),
                ('submission_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('submission_session_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.sessiontoken')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
