# Generated by Django 4.1.2 on 2022-10-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ip_address',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='user_agent',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
