# Generated by Django 4.1.2 on 2022-10-22 05:51

from django.db import migrations, models
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_ip_address_submission_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(null=True, upload_to=submission.models.assin_sub_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
