# Generated by Django 4.1.2 on 2022-10-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('submission', '0003_submission_submission_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('submission_course', 'submission_assignment')},
        ),
    ]
