# Generated by Django 4.1.2 on 2023-01-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_alter_submission_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
