# Generated by Django 4.1.2 on 2022-10-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_name', models.CharField(max_length=50)),
                ('desig_short', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.department')),
                ('teacher_desig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.designation')),
                ('teacher_institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institute')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
