# Generated by Django 4.1.2 on 2022-10-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name': 'Institute', 'verbose_name_plural': 'Institute'},
        ),
    ]
