# Generated by Django 4.1.2 on 2022-10-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_teacher_teacher_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=100),
        ),
    ]
