# Generated by Django 4.1.2 on 2022-10-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_teacher_teacher_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_course',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_session_token',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_dept',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_desig',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_institution',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='SessionToken',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
